### ISSUE TITLE
App Crash: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId

### ISSUE THREAD

**Issue by MrOlolo** [carrotquest/android-sdk#16]
**App crash at start with error.**

CarrotQuestSdk version: `io.carrotquest:android-sdk:1.0.32-commonRelease`

```
W/System.err(12196): io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
W/System.err(12196): 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
W/System.err(12196): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:126)
W/System.err(12196): 	at android.os.Handler.handleCallback(Handler.java:883)
W/System.err(12196): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err(12196): 	at android.os.Looper.loop(Looper.java:214)
W/System.err(12196): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(12196): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(12196): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err(12196): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
W/System.err(12196): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
W/System.err(12196): 	at io.carrotquest_sdk.android.data.service.CarrotService.initFirebaseService(CarrotService.java:1086)
W/System.err(12196): 	at io.carrotquest_sdk.android.data.service.CarrotService.access$100(CarrotService.java:65)
W/System.err(12196): 	at io.carrotquest_sdk.android.data.service.CarrotService$18.onNext(CarrotService.java:1146)
W/System.err(12196): 	at io.carrotquest_sdk.android.data.service.CarrotService$18.onNext(CarrotService.java:1140)
W/System.err(12196): 	at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:101)
W/System.err(12196): 	at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
W/System.err(12196): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
W/System.err(12196): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
W/System.err(12196): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
W/System.err(12196): 	... 7 more
W/System.err(12196): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/.../base.apk"],nativeLibraryDirectories=[/data/app/.../lib/x86, /data/app/.../base.apk!/lib/x86, /system/lib, /system/product/lib]]
W/System.err(12196): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
W/System.err(12196): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err(12196): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err(12196): 	... 16 more
W/System.err(12196): SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
W/System.err(12196): SLF4J: Defaulting to no-operation MDCAdapter implementation.
W/System.err(12196): SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
D/TransportRuntime.SQLiteEventStore(12196): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler(12196): Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=1932406068 in 1000ms(Backend next call timestamp 1627558605577). Attempt 1
E/AndroidRuntime(12196): FATAL EXCEPTION: main
E/AndroidRuntime(12196): Process: ..., PID: 12196
E/AndroidRuntime(12196): io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
E/AndroidRuntime(12196): 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
E/AndroidRuntime(12196): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:126)
E/AndroidRuntime(12196): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(12196): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(12196): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(12196): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(12196): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12196): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(12196): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(12196): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
E/AndroidRuntime(12196): 	at io.carrotquest_sdk.android.data.service.CarrotService.initFirebaseService(CarrotService.java:1086)
E/AndroidRuntime(12196): 	at io.carrotquest_sdk.android.data.service.CarrotService.access$100(CarrotService.java:65)
E/AndroidRuntime(12196): 	at io.carrotquest_sdk.android.data.service.CarrotService$18.onNext(CarrotService.java:1146)
E/AndroidRuntime(12196): 	at io.carrotquest_sdk.android.data.service.CarrotService$18.onNext(CarrotService.java:1140)
E/AndroidRuntime(12196): 	at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:101)
E/AndroidRuntime(12196): 	at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
E/AndroidRuntime(12196): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
E/AndroidRuntime(12196): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
E/AndroidRuntime(12196): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
E/AndroidRuntime(12196): 	... 7 more
E/AndroidRuntime(12196): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/.../base.apk"],nativeLibraryDirectories=[/data/app/..../lib/x86, /data/app/.../base.apk!/lib/x86, /system/lib, /system/product/lib]]
E/AndroidRuntime(12196): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime(12196): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(12196): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(12196): 	... 16 more
I/Process (12196): Sending signal. PID: 12196 SIG: 9
```

Need to fix firebase usage: https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId

**P.S.**
Fast fix for another users:
Add this line into implementation section (android/app/build.gradle)
`implementation("com.google.firebase:firebase-iid")`

**Comment by botalov** [comment]
We fixed this issue and updated the internal libs. Please update our SDK. Create a new issue If you can repeat it
