### ISSUE TITLE
java.lang.NoSuchMethodError: No static method userAgent

### ISSUE THREAD

**Issue by Pomeo777** [carrotquest/android-sdk#17]
Hi. In last library version I have  always got an  NoSuchMethodError when try to Carrot.setup(context, key, id). 
There is a stackTrace:
2021-09-02 16:45:33.045 7852-7852/someApk.consumer E/UncaughtException: java.lang.NoSuchMethodError: No static method userAgent()Ljava/lang/String; in class Lokhttp3/internal/Version; or its super classes (declaration of 'okhttp3.internal.Version' appears in /data/app/~~W2iU3wSqtzECg-q93nCZ-Q==/someApk.consumer-d35DYhZjZuUMHywe5N0L1A==/base.apk!classes5.dex)
        at io.carrotquest_sdk.android.core.main.CarrotSDK.commonSetup(CarrotSDK.java:155)
        at io.carrotquest_sdk.android.core.main.CarrotSDK.setup(CarrotSDK.java:135)
        at io.carrotquest_sdk.android.core.main.CarrotSDK.setup(CarrotSDK.java:131)
        at someApk.application.App.initCarrotQuest(App.java:193)
        atsomeApk.application.App.onCreate(App.java:72)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)

This error is alwaus generating in 131 line of CarrotSDK.class

**Comment by Pomeo777** [comment]
I found the problem. This is the okhttp3 library. In our project I am using v. 4+ and you are using version 3.12. +. So I had to downsize the version of this library. Everything is fine now, but this is not the best way to solve this problem.

**Comment by kva97** [comment]
Возникает ошибка:
java.lang.NoSuchMethodError: No static method userAgent()Ljava/Lang/String; in classLokhttp3
Возникает на этапе инициализации плагина CQ, при вызове метода Carrot.setup, после этого приложение крашится. 

Она является результатом несовместмости версий okhttp3 в разных плагинах/ библиотеках нашего проекта, так как мы используем актуальную версия API okhttp 4+, а в carrotquest/Android-SDK 3.12.+. 
 Для решения проблемы нужно со стороны carrotquest/Android-SDK поменять версию okhttp3 на 4.+ так как эти разные версии API okhttp3 не совместимы в одном проекте.

<img width="912" alt="Снимок экрана 2021-09-06 в 16 05 52" src="https://user-images.githubusercontent.com/49140450/132209072-3d5a4e3d-a6ed-47f3-93c7-2284adbf1516.png">
<img width="257" alt="Снимок экрана 2021-09-06 в 16 07 22" src="https://user-images.githubusercontent.com/49140450/132209082-7bdb5770-45fe-4000-9df0-160e1dfa4789.png">

**Comment by botalov** [comment]
Fixed in latest version
