### ISSUE TITLE
Проблема  с  добавлением фото

### ISSUE THREAD

**Issue by NChervinska** [carrotquest/android-sdk#21]
При попытке добавить фото в чат появляется сообщение об ошибке и закрывается приложение. Удалось воспроизвести на Android 7.0 и 12

```
FATAL EXCEPTION: main
E/AndroidRuntime(11693): Process: com, PID: 11693
E/AndroidRuntime(11693): java.lang.IllegalStateException: Unexpected rotation value -1
E/AndroidRuntime(11693): 	at androidx.camera.view.TransformUtils.surfaceRotationToRotationDegrees(TransformUtils.java:101)
E/AndroidRuntime(11693): 	at androidx.camera.view.PreviewTransformation.getTextureViewCorrectionMatrix(PreviewTransformation.java:151)
E/AndroidRuntime(11693): 	at androidx.camera.view.PreviewTransformation.transformView(PreviewTransformation.java:173)
E/AndroidRuntime(11693): 	at androidx.camera.view.PreviewViewImplementation.redrawPreview(PreviewViewImplementation.java:88)
E/AndroidRuntime(11693): 	at androidx.camera.view.PreviewViewImplementation.onSurfaceProvided(PreviewViewImplementation.java:95)
E/AndroidRuntime(11693): 	at androidx.camera.view.TextureViewImplementation.tryToProvidePreviewSurface(TextureViewImplementation.java:243)
E/AndroidRuntime(11693): 	at androidx.camera.view.TextureViewImplementation$1.onSurfaceTextureAvailable(TextureViewImplementation.java:141)
E/AndroidRuntime(11693): 	at android.view.TextureView.getTextureLayer(TextureView.java:404)
E/AndroidRuntime(11693): 	at android.view.TextureView.draw(TextureView.java:353)
E/AndroidRuntime(11693): 	at android.view.View.updateDisplayListIfDirty(View.java:21880)
E/AndroidRuntime(11693): 	at android.view.View.draw(View.java:22738)
E/AndroidRuntime(11693): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
E/AndroidRuntime(11693): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
E/AndroidRuntime(11693): 	at android.view.View.draw(View.java:23016)
E/AndroidRuntime(11693): 	at android.view.View.updateDisplayListIfDirty(View.java:21880)
E/AndroidRuntime(11693): 	at android.view.View.draw(View.java:22738)
E/AndroidRuntime(11693): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
E/AndroidRuntime(11693): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
E/AndroidRuntime(11693): 	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
E/AndroidRuntime(11693): 	at android.view.View.updateDisplayListIfDirty(View.java:21871)
E/AndroidRuntime(11693): 	at android.view.View.draw(View.java:22738)
E/AndroidRuntime(11693): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
E/AndroidRuntime(11693): 	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
E/AndroidRuntime(11693): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
E/AndroidRuntime(11693): 	at android.view.View.draw(View.java:23016)
```

**Comment by botalov** [comment]
Добрый день! Прошу прощения за долгое ответ. Воспроизвести проблему (в том числе на устройствах с указанными версиями ОС) не удалось, но, так как ошибка внутри библиотеки от гугл, мы поискали подобные проблемы в других проектах в интернете и нашли один подобный случай, который решился обновлением этой самой библиотеки. Мы то же самое сделали у себя и выкатим этот фикс в ближайшем релизе (ориентировочно, в течении недели, зависит еще от других задач).
Если Вы заметили какие-то другие моменты кроме версий ОС, от которых зависит воспроизводимость данной проблемы, буду рад услышать.
